### ISSUE TITLE
Scheduling a Personal Activity - forced to select an Account

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#13]
Even though there is a comment to the same (pers activity does not require an account) - the system is forcing one to select one.

**Comment by rjledger** [comment]
Is this going to get fixed in 1.2?

**Comment by wskidmore** [comment]
I can't seem to reproduce this issue - not sure if I'm approaching it from a different angle?
1. Login (as admin, lee doesn't have activity permissions at the moment) 
2. Select Calendar
3. Click +
4. Select Personal Activity
5. Click Save

Takes me back to Calendar View with a blank (no description/account/contact info) personal activity (on both 1.2 and master branch)

![screen shot showing blank activities](http://i40.tinypic.com/t88dxg.png)

**Comment by rjledger** [comment]
Sometimes one schedules a per activity w/a contact... Mobile web will not let you do that...

Also, The normal way folks have been scheduling (all types of) activities (forever) has been to select a Contact first.... Windows/LAN works this way and so does web... Mobile is backwards.... We have had to disable validation on Account for customers so that they could work the way they expected Mobile to work.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
Using these steps:
1. Login
2. Select Contacts
3. Select Related - Activities
4. Click +
5. Click Save

You get the same result. But I do see what you mean if you follow these steps:
1. Click Calendar
2. Click +
3. Click Personal Activity
4. Try to click Contact

You get a box stating an account is required. This is by design so when you do click Contact it gives you only members of that organization. I can see the potential issue here - why make a user go through 3+ screen transitions?

I just checked the Web, and instead of making the user choose the Account first, you can choose just the Contact and it does another request (?) to find that contacts associated Account.

**Comment by rjledger** [comment]
Actually... If you look at Windows/LAN.. if you choose a contact - it pre-fills in the Account so the user does not have to.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
Right, it is the same with the Web client - meaning it's not so much a validation logic bug in Mobile (what I was originally hoping for) but more of a design change/feature to get the additional info automatically for the user.

**Comment by rjledger** [comment]
You have the necessary AccountID and AccountName as part of the Contact SData payload already... ;-)
You do not need to go back to get it.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
Several cases going on:

Contact -> Contact Detail -> Related Activities -> New Activity
This automatically fills out the Account and the Contact fields.

Calendar -> New Activity
This automatically fills out the StartDate based on the Calendar. Account and Contact are empty. Clicking Contact requires Account in Mobile only.

So in the second case, Contact uses the Lookup control, which is a general-use control and only "passes back" the value of the item selected and the $key - something like:

   {key: "CGHEA0002670", text: "Abbott, John"}

Then text gets formatted/rendered and set to the input field on the view. In the case of Contact, the key gets set to ContactId and text to ContactName.

So it'd need to take the key and grab the AccountName off a new request. Or otherwise somehow not use the generic lookup or override it or something else that I'm not thinking of at the moment - but I will keep thinking about some different ways to approach it.

**Comment by rjledger** [comment]
Interesting challenge!

## 

RJ Ledger - rjlSystems
Web:www.rjlsystems.net
Blog: blog.rjlsystems.net
rjledger@rjlsystems.net
+1. 508.809.9513
Sent from Samsung tablet
Tony Skidmore reply@reply.github.com wrote:
Several cases going on:

Contact -> Contact Detail -> Related Activities -> New Activity
This automatically fills out the Account and the Contact fields.

Calendar -> New Activity
This automatically fills out the StartDate based on the Calendar. Account and Contact are empty. Clicking Contact requires Account in Mobile only.

So in the second case, Contact uses the Lookup control, which is a general-use control and only "passes back" the value of the item selected and the $key - something like:

   {key: "CGHEA0002670", text: "Abbott, John"}

Then text gets formatted/rendered and set to the input field on the view. In the case of Contact, the key gets set to ContactId and text to ContactName.

So it'd need to take the key and grab the AccountName off a new request. Or otherwise somehow not use the generic lookup or override it or something else that I'm not thinking of at the moment - but I will keep thinking about some different ways to approach it.

##

**Comment by rjledger** [comment]
Has actually been changed/fixed sometime ago.
