### ISSUE TITLE
Master - dojo based - All works... but roles/securedActions seem to not "work"

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#20]
Was able to get in OK using admin user.. but if I use someone else, the new security is giving me problems.

I added roles and securedActions in SData, rebuilt/deployed.. but it does not seem to work. Am I missing something?

**Comment by jhershauer** [comment]
The current master code is going to require an 8.0 SData provider with the logged in user assigned to a role. You should stay on the v1.2 code-base with a 7.5.4 DB. We ARE looking into gracefully degrading so that you'll be able to run all of the new dojo-based stuff on a 7.5.4 environment.

On Oct 26, 2011, at 6:57 PM, RJ Ledger wrote:

Was able to get in OK using admin user.. but if I use someone else, the new security is giving me problems.

I added roles and securedActions in SData, rebuilt/deployed.. but it does not seem to work. Am I missing something?

## 

Reply to this email directly or view it on GitHub:
https://github.com/SageScottsdalePlatform/argos-saleslogix/issues/20

**Comment by rjledger** [comment]
Hi Jeff,
 Thanks for the response.
So you are saying, there are some additional changes in SData coming in the area of Roles/Secured Actions, etc we just don't have right now in the 7.5.4.xxxx which are more than enabling additional SData feeds in AA - right?

FYI - I was quickly able to shut off the new security and the dojo based version is all running fine in our dev/demo 7.5.4 as well as our production system we use every day. Like the device "sensitive" changes it has. It would be great to be able to tap into that so that we can do some unique tablet based things (I have a Samsung Galaxy 10.1 tablet... it's fantastic w/the mobile web app).

Ques.. will we be using the dojo based code at BootCamp?

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
The "fallback"mode for 7.5.4 is working very well. This is good since we can run this against the current released version on production db's.
Thanks!
