### ISSUE TITLE
3.1 beta 2 - breaks all sorts of customizations

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#279]
For example.. we add  properties/fields to detail/edit view for Account and/or Contact using the:
  registerCustomization
     at: function(row) { return row.name == 'Status'; },
        type: 'insert' ....

nothing shows up... runs fine in all 3.0.x

FYI - I have not tested the OOTB argos-sample but our customs don't do anything different than the sample does.

**Comment by jbest84** [comment]
I ran the argos-sample against beta2 in dev mode yesterday. I updated index-dev-sample.html in the argos-sample project. There were a couple of script references that had to be added/changed.

**Comment by rjledger** [comment]
Have you put it "inside" the AA as a custom module and deployed? - This is where I am seeing issues.

**Comment by jbest84** [comment]
OK - AA does a few things when it deploys a custom module. Can you answer a few questions?

Is your javascript being deployed to the portal (content/javascript/<your-module-name.js>)?

Can you open your deployed index.aspx, is your script from the first question included in the `<!-- Modules -->` section?

AA builds your release.jsb, and then updates the index.aspx file to include the script.

**Comment by rjledger** [comment]
Yes….

Yep
Yep

Oh yes.. I deployed another custom module that has a list view which uses "GroupList".. and expects it to open "collapsed". .. well it does not.

So there's a bunch of things that are making custom modules (I have a about a dozen of them) to not work/look like they did under 3.0.x

On Q1 - I see things (additional email fields) show up on the Edit view.. but not the detail view - this is true for Account, Contact, and Lead. .. and firebug says no errors!
.. Humm what happened to the "More details" section in Account(s) Detail view?? - not there!

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by rjledger** [comment]
OK.. additional info on the OOTB (pulled my custom(s)):
    If you look at a contact detail (view) you will see the More Details is "expanded" - it is supposed to be collapsed.. and there's no "control" there to collapse it.. and no section control to collapse Details or Related items as well. - somethings "broken" and I believe it's at the heart of what is causing me problems w/customs that work fine in 3.0.x

**Comment by rjledger** [comment]
The lack of collapse capability is a problem in every entity in every detail view.

**Comment by jbest84** [comment]
Collapsed/expanded was removed from details back in March as part of our design change: https://github.com/Saleslogix/argos-sdk/commit/952d47ff6a21407fb4f66fe3c28845fb9b4e8b41#diff-4

**Comment by rjledger** [comment]
Major bummer –  I just attempted to put this back and the result was a complete mess…

Disclaimer – the following is not a negative comment about the technical quality of the  change.. but an honest comment about it’s very negative  impact to existing customers and partners:

IMHO the 3.1 release is not looking good and what is going to happen is we will have to charge our customers several thousand $$$ to put it “back” to the way it needs to be so that it does not break existing customizations. Of course they are going to balk on it and ask why SLX made such “breaking changes – and my answer will have to be the truth.. partners were not shown/asked and it was done in a vacuum in AZ… There needs to be an open review of these changes w/the partner community.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by rjledger** [comment]
This does not explain why Grouped list views fail to open “collapsed – do you know what change were made that break this?

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by jbest84** [comment]
The grouped list issue is most likely a defect. 

The detail changes should not be breaking any fields you are trying to add or remove. We no longer show fields that have no values bound to them in detail, that is why you see them in edit and not in detail. I would not consider the detail changes "breaking changes". We no longer support a feature there that we felt was not needed and confusing. I linked you the exact change set to revert if you wanted that feature back (you of course would have to modify the styling to make it look right with the new theme). I don't see how that could possibly be thousands of dollars worth of work. I would be more than willing to add it to the argos-sample if you want.

We released beta1 on July 31st. We received almost no feedback. The detail change has been in the development branch since March. This change was not done in a vacuum. This project is completely open source. Partners are free to review what we are working on at any time.

**Comment by jperona** [comment]
Ok we will need to be quite aware of what's breaking

Anything that breaks a customization should be something we evaluate

Sent from my iPhone

On Sep 18, 2014, at 2:43 PM, Jason Best <notifications@github.com<mailto:notifications@github.com>> wrote:

The grouped list issue is most likely a defect.

The detail changes should not be breaking any fields you are trying to add or remove. We no longer show fields that have no values bound to them in detail, that is why you see them in edit and not in detail. I would not consider the detail changes "breaking changes". We no longer support a feature there that we felt was not needed and confusing. I linked you the exact change set to revert if you wanted that feature back (you of course would have to modify the styling to make it look right with the new theme). I don't see how that could possibly be thousands of dollars worth of work. I would be more than willing to add it to the argos-sample if you want.

We released beta1 on July 31st. We received almost no feedback. The detail change has been in the development branch since March. This change was not done in a vacuum. This project is completely open source. Partners are free to review what we are working on at any time.

##

**Comment by jbest84** [comment]
GroupedList issue fixed here: https://github.com/Saleslogix/argos-sdk/commit/01adf09b5a1b6c1d1a818d993a6898482828bd5f
