### ISSUE TITLE
Latest changes for Contact Assn to Opp

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#31]
Noticed changes for contract too.. contracts are not associated w/opp.s

Is the plan to add in the assn to Accounts?

**Comment by wskidmore** [comment]
Contract Views were deleted in a previous commit, but the List view is used by Tickets.. I was just restored that piece.

I do plan to make the Associate View more generic so that it can be passed the parent entity/resource kind so it updates the right feed -- this is the initial proof of concept while working out the UI, flow, what it should filter, etc. Will definitely see more updates to it this week.

**Comment by rjledger** [comment]
Yep.. I thought that was what was going on... (I also have the "complete source w/contracts, etc... in my version ;-)

I also plan on doing some "hacking" on MW next week (not enough snow to ski yet.. and too expensive between Christmas & New Year). Maybe I'll make some posts ...

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
