### ISSUE TITLE
Vers 3.2.0 - Click Refresh in my activities does NOT check the date

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#321]
Scenario:
     On current date - all ok
     Go past midnight click refresh - still shows my activities as though it is the day before
     Go to Calendar - select "Today" - changes calendar to current date and refreshes calendar
     Go back to my activities and click refresh - no change - still displays like it is "yesterday"

only a FULL browser refresh will force it to go to the current date.

**Comment by jbest84** [comment]
The default hash tag executes and saves the results of that search to this.query in _ListBase line 1168 (SDK). For the case of the #today hash tag it will execute the function which calculates the current date. If you want you can override _refreshClicked in MyList.js and use "this.searchWidget.search()". Keep in mind though, if the user changed some text and didn't click enter on the search, doing it this way would use that query instead of the original that they intended on refreshing.

**Comment by rjledger** [comment]
I see this has been tagged as a sdk defect - have you got a fix yet that I might plug into my (production) code? It is a bit of a pita to have to do a browser refresh.

**Comment by jbest84** [comment]
There is not a fix in place yet. You can work around the issue by searching for something else and re-searching #today

**Comment by rjledger** [comment]
Tried it.. does not work

Sent by Outlookhttp://taps.io/outlookmobile for Android

On Fri, Feb 6, 2015 at 8:42 AM -0800, "Jason Best" <notifications@github.com<mailto:notifications@github.com>> wrote:

There is not a fix in place yet. You can work around the issue by searching for something else and re-searching #today

**Comment by jbest84** [comment]
Fixed in changeset: https://github.com/Saleslogix/argos-sdk/commit/3aacb0a3e7acd3f4ee0f279af4222286754ee3a0

Closes MBL-10847
