### ISSUE TITLE
Latest master - Getting the incorrect view on my Samsung Galaxy 10.1 tab

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#33]
When the tablet is in the portrait mode, I am seeing the calendar showing  "side-by-side" view - when in landscape it is showing the calendar over activity/event view.

Seems backwards.. ;-)

**Comment by wskidmore** [comment]
This appears to be an issue with just the Galaxy Tab 10.1. ReUI relies on `window.orientation` property to determine landscape/portrait where:

`window.orientation  = degrees of tilt of device`

So ReUI assumes `90` and `-90` to be rotated, and therefore landscape.

Galaxy Tab (10.1) reports a tilt of `0` for landscape (since it is the default I guess) and `90` for portrait. Whereas all other devices so far report `0` for portrait and `90` for landscape. 

Looking into comparing height/widths but it appears that for iOS devices (phones and tablets) the `width` and `height` values are constant and do not change on rotation. And Android appears to have issues with height/width onload... http://code.google.com/p/android/issues/detail?id=12455

**Comment by rjledger** [comment]
Wonder if this is an issue w/all Samsung devices?
I've got droid 3.2 (latest release) on it.

It's OK on my Moto DroidX

Any way to detect the Galaxy difference?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
From more research it appears that for Android (all versions), `window.orientation` is set assuming the "default" state as `0`. So for the Playbook, Xoom and Galaxy Tab 10.1 all behave in this way and I would expect any future tablet that is held landscape as default to also report `0`.

Looking into perhaps a mashup of the `onorientationchange` event and `onresize` event as it appears all Androids DO update their width/height when rotated.

**Comment by rjledger** [comment]
Interesting...
I just noticed that on my moto DroidX (droid 2.3.3) that if year is selected (calendar) it makes no diff in portrait/landscape... looks landscape all the time (one over the other). Screen size issue?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
The Droid X with Year view was a design decision, well, technical restriction. The width of ~800px could fit 2 months, and ~1000px with 3 months.

Setting a media query with min-width of 800px would logically work, but the media query width value is not updated on orientation change (some devices do, others don't). 

The next step was setting min-width to 480px, but then you get devices that are that same width, but not as tall as the Droid X and when landscape do not have enough room and only show 1 tiny month at a time. 

Changing it to min-height 800 was considered, but broke several tablets that did update on orientation change.

The end result was to set it to min-width of 768px (1024x768). This would work with browsers and all tablets, but exclude all phones.

**Comment by rjledger** [comment]
Sounds just fine.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
This had to be done at the ReUI level, but from emulator testing all seems well:

https://github.com/Sage/argos-sdk/commit/f4fc310ef34abeac251c5a4dd8d4ef64d2573219

**Comment by rjledger** [comment]
Thanks! I'll test it tomorrow am.
rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
