### ISSUE TITLE
3.3 release breaks existing custom modules that worked w/3.2.1

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#346]
Getting a strange error in Firebug (Error: Tried to register widget with id==configure_quickactions but that id is already registered). 

I even pulled all except one simple one (parent add-on) and still no joy.

**Comment by jbest84** [comment]
Can you try removing `this.inherited(arguments);` from loadViews and loadCustomizations in your ApplicationModule.js?

**Comment by jbest84** [comment]
The problem is our sample module incorrectly uses this.inherited. The only module that should be calling this.inherited is our based application module. Other customization modules are loaded in side by side through the modules array (you can see this in configuration/development.js). Before it was OK, because the SDK didn't add any of it's own views. Now it does, and each loaded module is trying to call into the base, it looks like this:

argos-saleslogix\src\ApplicationModule::loadViews -> calls this.inherited which invokes argos-sdk\src\ApplicationModule::loadViews

argos-sample\src\ApplicationModule::loadViews -> calls this.inherited which also invokes argos-sdk\src\ApplicationModule::loadViews

We can probably put in a flag at the SDK level so it won't execute twice, if an application module incorrectly invokes this.inherited.

**Comment by rjledger** [comment]
Tried – no diff.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
Try the commit I just referenced: https://github.com/Saleslogix/argos-sdk/commit/3415e4b30f657fa27c38f63518af409230ddfc95

**Comment by rjledger** [comment]
Just hacked it in. Most working but I’m seeing one custom not quite working. It’s the “parent” one. It’s right out of the sample as an individual (custom) module and deployed like the rest thru the “AA”. It’s sitting there saying loading… for the parent value.

AH - it is throwing an error related to dojo:
       dojo.removeclass is not a function 

I see where you changed it in the sample - making the same change.

Have you guys run in the sample and tested all of it?
rj

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by rjledger** [comment]
I will go thru a full regression test of all my custom modules and post results.

**Comment by rjledger** [comment]
All modules working.

**Comment by jbest84** [comment]
Thanks for the feedback.
