### ISSUE TITLE
RE: Localization -> New Help Folder

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#5]
Just re-loaded my test system to dig deeper into another issue and saw a new "error" popup in Firebug - Missing help-en_US.html.

For now I just copied the help.html and renamed it help-en_US.html.

You guys probably already know about this one.

**Comment by jhershauer** [comment]
This isn't causing any problem on my machine. Are you just saying that you see the 404 error in the console? This is expected behavior. 

The functionality should be that if it doesn't find a language-specific help file (404 not found), it falls back on the default help.html. After that, it will be cached, so it's not like there will be an extra request every time you hit the help file.

**Comment by rjledger** [comment]
No - not causing any problem and it "fell back" as I'd expected it would. Just wondering if there was going to be a specific en-US file.

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
No. The default help file is English.

**Comment by rjledger** [comment]
OK..

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
